use dtb_prj
go

/*INSERE CONFIGURAÇÃO DA EMPRESA*/
INSERT INTO TS_CONFI(DS_CONFIGU, TP_CONFIGU, LG_CONFIGU) VALUES('Empresa trabalha aos fins de semana', 'WWEND', 'T')


/*INSERE CLIENTES PARA TESTES*/
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CNPJCLI) VALUES('CONSTRUTORA BOBS', '32.123.423/0001-12')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CNPJCLI) VALUES('CONSTRUTORA BK', '74.987.745/0001-52')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CNPJCLI) VALUES('CONSTRUTORA MCDO', '54.546.875/0001-23')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CNPJCLI) VALUES('CONSTRUTORA MADERO', '55.846.214/0001-43')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CPFCLIE) VALUES('JOSÉ CLAUDIO VIERA', '123.852.547-89')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CPFCLIE) VALUES('JUAN DELAVEGA', '541.654.842-10')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CPFCLIE) VALUES('EDNA VIEIRA', '987.645.846-25')
INSERT INTO CG_CLIEN(DS_CLIENTE, NM_CPFCLIE) VALUES('FERNANDO MUIDA', '852.258.357-91')


/*INSERE PRODUTOS PARA TESTES*/
INSERT INTO CG_PRODU(DS_PRODUTO,VL_PRODUTO, DS_CORPROD) VALUES('PISO DE PORCELANATO', 182.21, 'BRANCO')
INSERT INTO CG_PRODU(DS_PRODUTO,VL_PRODUTO, DS_CORPROD) VALUES('MADEIRA DE EUCALIPTO', 182.21, 'MADEIRA')
INSERT INTO CG_PRODU(DS_PRODUTO,VL_PRODUTO, DS_CORPROD) VALUES('PORTÃO DE FERRO', 182.21, 'PRETO')
INSERT INTO CG_PRODU(DS_PRODUTO,VL_PRODUTO) VALUES('SACO DE CIMENTO 50KG', 182.21)


/*INSERE VENDAS PARA TESTES*/
DECLARE @DATE DATETIME
SELECT @DATE = MAX(DT_SISTEMA) FROM CG_DATAS
DECLARE @DATE_ENT DATETIME = DATEADD(MONTH, 1, @DATE)
INSERT INTO CG_VENDA(CD_IDVENDA, CD_PRODUTO, QT_PRODUTO, CD_CLIENTE, DT_FATURAM, DT_ENTREGA) VALUES(1, 1, 4, 2, @DATE, @DATE_ENT)
INSERT INTO CG_VENDA(CD_IDVENDA, CD_PRODUTO, QT_PRODUTO, CD_CLIENTE, DT_FATURAM, DT_ENTREGA) VALUES(1, 2, 12, 2, @DATE, @DATE_ENT)
INSERT INTO CG_VENDA(CD_IDVENDA, CD_PRODUTO, QT_PRODUTO, CD_CLIENTE, DT_FATURAM, DT_ENTREGA) VALUES(1, 3, 1, 2, @DATE, @DATE_ENT)
INSERT INTO CG_VENDA(CD_IDVENDA, CD_PRODUTO, QT_PRODUTO, CD_CLIENTE, DT_FATURAM, DT_ENTREGA) VALUES(2, 1, 14, 1, @DATE, @DATE_ENT)
INSERT INTO CG_VENDA(CD_IDVENDA, CD_PRODUTO, QT_PRODUTO, CD_CLIENTE, DT_FATURAM, DT_ENTREGA) VALUES(2, 4, 31, 1, @DATE, @DATE_ENT)
