CREATE VIEW VW_CX_MOCON_TOTAL AS
SELECT CG_CLIEN.DS_CLIENTE,
       FORMAT(SUM(CX_MOCON.VL_TOTALVE), 'N2') AS VL_TOTAMES,
       MIN(CX_MOCON.DT_FATURAM) AS PRIMEIRO_PEDIDO,
       MAX(CX_MOCON.DT_FATURAM) AS ULTIMO_PEDIDO,
       COUNT(CX_MOCON.CD_IDVENDA) AS QNT_PEDIDOS
FROM CX_MOCON
INNER JOIN CG_CLIEN ON CG_CLIEN.ID_CLIENTE = CX_MOCON.CD_CLIENTE
GROUP BY CG_CLIEN.DS_CLIENTE
