CREATE VIEW VW_CX_MOCON AS
SELECT CG_CLIEN.DS_CLIENTE,
	   CX_MOCON.CD_IDVENDA,
	   CX_MOCON.VL_TOTALVE,
	   CX_MOCON.DT_FATURAM,
	   CX_MOCON.DT_ENTREGA
FROM CX_MOCON
INNER JOIN CG_CLIEN ON CG_CLIEN.ID_CLIENTE = CX_MOCON.CD_CLIENTE