use dtb_prj
go

CREATE OR ALTER PROC dbo.SP_OCV1_GENERATE_MOCON(
	@DATE date
)
AS
BEGIN

	DECLARE
		@DS_PROCESS VARCHAR(250),
		@COUNT INT,
		@COUNT2 INT,
		@COUNT3 INT,
		@WCD_IDVENDA INT,
		@WCD_PRODUTO INT,
		@WQT_PRODUTO INT,
		@WCD_CLIENTE INT,
		@WDT_FATURAM DATETIME,
		@WDT_ENTREGA DATE,
		@VL_PRODUTO FLOAT,
		@VL_TOTVEND FLOAT,
		@VL_TOTALVE FLOAT,
		@ERROR VARCHAR(MAX),
		@WWEND VARCHAR(1),
		@LG_FIMSEMA VARCHAR(1)


	SET @DS_PROCESS = 'GERAÇÃO DE CONTABILIDADE DE VENDAS DIÁRIAS'


	--DELETA CASO TENHA DADO ERRO PARA RODAR NOVAMENTE
	IF (SELECT COUNT(1) FROM TS_PROCE WHERE DT_ERROPRO IS NOT NULL AND
	                                        DS_PROCESS = @DS_PROCESS) > 0
		DELETE FROM TS_PROCE WHERE DS_PROCESS = @DS_PROCESS

	
	IF (SELECT COUNT(1) FROM CG_VENDA WHERE CAST(DT_FATURAM AS DATE) = @DATE) > 0 AND
	   (SELECT COUNT(1) FROM TS_PROCE WHERE DT_FIMPROC IS NOT NULL AND
	                                        DS_PROCESS = @DS_PROCESS) = 0
	BEGIN
		
		/*MARCAÇÃO NA TABELA DE CONTROLE DE PROCESSOS*/
		INSERT INTO TS_PROCE(DT_SISTEMA, DS_PROCESS, DT_INIPROC)
		VALUES(@DATE, @DS_PROCESS, GETDATE())


		/*INÍCIO TABELAS TEMPORÁRIAS*/
		CREATE TABLE #CG_VENDA(
			CD_IDVENDA INT NOT NULL,
			CD_PRODUTO INT NOT NULL,
			QT_PRODUTO INT NOT NULL,
			CD_CLIENTE int NOT NULL,
			DT_FATURAM DATETIME NOT NULL,
			DT_ENTREGA DATE NOT NULL
		)

		CREATE TABLE #LANCAMENTOS(
			VL_TOTVEND FLOAT,
			CD_IDVENDA INT,
			CD_CLIENTE INT,
			DT_FATURAM DATETIME,
			DT_ENTREGA DATE
		)

		INSERT #CG_VENDA(
			CD_IDVENDA,
			CD_PRODUTO,
			QT_PRODUTO,
			CD_CLIENTE,
			DT_FATURAM,
			DT_ENTREGA) 
		
		SELECT CD_IDVENDA,
			   CD_PRODUTO,
			   QT_PRODUTO,
			   CD_CLIENTE,
			   DT_FATURAM,
			   DT_ENTREGA
		FROM CG_VENDA 
		WHERE CAST(DT_FATURAM AS DATE) = @DATE
		/*FIM TABELAS TEMPORÁRIAS*/

		
		--INICIA PROCESSO
		BEGIN TRY

			BEGIN TRAN WORK

			SET @COUNT = (SELECT COUNT(1) FROM #CG_VENDA)

			WHILE @COUNT > 0
			BEGIN
			
				SELECT TOP (1) @WCD_IDVENDA = CD_IDVENDA,
				               @WCD_PRODUTO	= CD_PRODUTO,
							   @WQT_PRODUTO	= QT_PRODUTO,
							   @WCD_CLIENTE	= CD_CLIENTE,
							   @WDT_FATURAM	= DT_FATURAM,
							   @WDT_ENTREGA = DT_ENTREGA
				FROM #CG_VENDA
				
				SELECT @VL_PRODUTO = VL_PRODUTO FROM CG_PRODU WHERE CD_PRODUTO = @WCD_PRODUTO 

				SET @VL_TOTVEND = @WQT_PRODUTO * @VL_PRODUTO

				INSERT INTO #LANCAMENTOS VALUES(@VL_TOTVEND, @WCD_IDVENDA, @WCD_CLIENTE, @WDT_FATURAM, @WDT_ENTREGA)

				SET @COUNT2 = @COUNT2 - 1

				DELETE TOP (1) FROM #CG_VENDA
				SET @COUNT = @COUNT - 1
			
			END


			SELECT @COUNT3 = COUNT(DISTINCT CD_IDVENDA) FROM #LANCAMENTOS 

			WHILE @COUNT3 > 0
			BEGIN
				
				SELECT @VL_TOTALVE = SUM(VL_TOTVEND) FROM #LANCAMENTOS WHERE CD_IDVENDA = @COUNT3

				/*VERIFICA SE A EMPRESA ESTÁ GERANDO VENDAS NO FIM DE SEMANA
				PARA ADICIONAR 50% NOS VALORES*/
				SELECT @WWEND = LG_CONFIGU FROM TS_CONFI WHERE TP_CONFIGU = 'WWEND'
				SELECT @LG_FIMSEMA = LG_FIMSEMA FROM CG_DATAS WHERE DT_SISTEMA = @DATE
				
				IF (upper(@WWEND) = 'T') AND (upper(@LG_FIMSEMA) = 'T')
					SET @VL_TOTALVE = @VL_TOTALVE + (@VL_TOTALVE * 0.5)

				INSERT INTO CX_MOCON(CD_IDVENDA, CD_CLIENTE, VL_TOTALVE, DT_FATURAM, DT_ENTREGA) 
				VALUES(@WCD_IDVENDA, @WCD_CLIENTE, @VL_TOTALVE, @WDT_FATURAM, @WDT_ENTREGA)

				DELETE FROM #LANCAMENTOS WHERE CD_IDVENDA = @WCD_IDVENDA

				SET @COUNT3 = @COUNT3 - 1
				
			END
			

			/*MARCA O SUCESSO NO PROCESSAMENTO*/
			UPDATE TS_PROCE 
			SET DT_FIMPROC = GETDATE() 
			WHERE DS_PROCESS = @DS_PROCESS


			IF @@TRANCOUNT > 0
				COMMIT WORK
		
		END TRY
		BEGIN CATCH

			SELECT @ERROR = SubString( 'Erro : ' + Convert(VarChar,@@Error) + ' - ' + ERROR_PROCEDURE() + ' (' + Convert(VarChar,ERROR_LINE()) + ')'+ ERROR_MESSAGE() , 1, 255)

			UPDATE TS_PROCE
			SET DT_ERROPRO = GETDATE(),
			    DS_ERROPRO = @ERROR
			WHERE DS_PROCESS = @DS_PROCESS

			IF @@TRANCOUNT > 0
				ROLLBACK WORK

		END CATCH

		DROP TABLE #CG_VENDA
		DROP TABLE #LANCAMENTOS

	END
END