use dtb_prj
go

CREATE OR ALTER PROC dbo.SP_CHANGE_DATE_SYSTEM(
	@DATE date
)
AS
BEGIN

	DECLARE 
		@NEXTDATE DATE,
		@DAY varchar(8),
		@LG_WEEKEND varchar(1),
		@LG_VERIFIC varchar(1),
		@LG_SISFECH varchar(1),
		@WWEND varchar(1)

	
	SELECT @WWEND = LG_CONFIGU FROM TS_CONFI WHERE TP_CONFIGU = 'WWEND'

	SELECT @LG_SISFECH = LG_SISFECH FROM CG_DATAS WHERE DT_SISTEMA = @DATE

	IF @LG_SISFECH = 'T'
	BEGIN

		IF upper(@WWEND) = 'F'
		BEGIN
	
			SET @NEXTDATE = DATEADD(DAY, 1, @DATE)
			SET @DAY = DATENAME(WEEKDAY, @NEXTDATE)

			WHILE (@DAY = 'SUNDAY') OR (@DAY = 'SATURDAY')
			BEGIN
				SET @NEXTDATE = DATEADD(DAY, 1, @NEXTDATE)
				SET @DAY = DATENAME(WEEKDAY, @NEXTDATE)
				SET @LG_VERIFIC = 'T'
			END

			IF @LG_VERIFIC = 'T'
				INSERT INTO CG_DATAS(DT_SISTEMA) VALUES(@NEXTDATE)
			ELSE
			IF (@DAY <> 'SUNDAY') OR (@DAY <> 'SATURDAY')
			BEGIN

				SET @NEXTDATE = DATEADD(DAY, 1, @DATE)
				INSERT INTO CG_DATAS(DT_SISTEMA) VALUES(@NEXTDATE)

				UPDATE CG_DATAS SET LG_SISABER = 'T' WHERE DT_SISTEMA = @NEXTDATE

			END

		END

		IF upper(@WWEND) = 'T'
		BEGIN

			SET @NEXTDATE = DATEADD(DAY, 1, @DATE)
			SET @DAY = DATENAME(WEEKDAY, @NEXTDATE)

			IF (@DAY = 'SUNDAY') OR (@DAY = 'SATURDAY')
				SET @LG_WEEKEND = 'T'
			ELSE
				SET @LG_WEEKEND = 'F'
			
			INSERT INTO CG_DATAS(DT_SISTEMA, LG_FIMSEMA) VALUES(@NEXTDATE, @LG_WEEKEND)

			UPDATE CG_DATAS SET LG_SISABER = 'T' WHERE DT_SISTEMA = @NEXTDATE

		END

	END
 
END