use dtb_prj
go

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CG_VENDA')
BEGIN
	CREATE TABLE CG_VENDA(
		NM_SEQUENC INT PRIMARY KEY IDENTITY NOT NULL,
		CD_IDVENDA INT NOT NULL,
		CD_PRODUTO INT NOT NULL,
		QT_PRODUTO INT NOT NULL,
		CD_CLIENTE int NOT NULL,
		DT_FATURAM DATETIME NOT NULL,
		DT_ENTREGA DATETIME NOT NULL
	)
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CG_PRODU')
BEGIN
	CREATE TABLE CG_PRODU(
		CD_PRODUTO INT PRIMARY KEY IDENTITY NOT NULL,
		DS_PRODUTO VARCHAR(250) NOT NULL,
		VL_PRODUTO FLOAT NOT NULL,
		DS_CORPROD VARCHAR(30)
	)
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CX_MOCON')
BEGIN
	CREATE TABLE CX_MOCON(
		CD_MOVIMEN INT PRIMARY KEY IDENTITY NOT NULL,
		CD_IDVENDA INT NOT NULL,
		CD_CLIENTE INT NOT NULL,
		VL_TOTALVE FLOAT NOT NULL,
		DT_FATURAM DATETIME NOT NULL,
		DT_ENTREGA DATETIME NOT NULL	
	)
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CG_CLIEN')
BEGIN
	CREATE TABLE CG_CLIEN(
		ID_CLIENTE INT PRIMARY KEY IDENTITY NOT NULL,
		DS_CLIENTE VARCHAR(250) NOT NULL,
		NM_CPFCLIE VARCHAR(14) NULL,
		NM_CNPJCLI VARCHAR(18) NULL,
		VL_TOTFATU FLOAT NOT NULL DEFAULT(0),
		VL_TOTLUCR FLOAT NOT NULL DEFAULT(0)
	)
	CREATE UNIQUE INDEX IDX_UNIQUE_CPF ON CG_CLIEN (NM_CPFCLIE) WHERE NM_CPFCLIE IS NOT NULL
	CREATE UNIQUE INDEX IDX_UNIQUE_CNPJ ON CG_CLIEN (NM_CNPJCLI) WHERE NM_CNPJCLI IS NOT NULL
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CG_DATAS')
BEGIN
	CREATE TABLE CG_DATAS(
		DT_SISTEMA DATE NOT NULL UNIQUE,
		LG_SISFECH VARCHAR(1) DEFAULT('F'),
		LG_SISABER VARCHAR(1) DEFAULT('F'),
		LG_ABERINI VARCHAR(1) DEFAULT('F'),
		LG_FECHINI VARCHAR(1) DEFAULT('F'),
		LG_FIMSEMA VARCHAR(1) DEFAULT('F')
	)
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TS_PROCE')
BEGIN
	CREATE TABLE TS_PROCE(
		CD_PROCESS INT PRIMARY KEY IDENTITY NOT NULL,
		DT_SISTEMA DATE,
		DS_PROCESS VARCHAR(250),
		DT_INIPROC DATETIME,
		DT_FIMPROC DATETIME,
		DT_ERROPRO DATETIME,
		DS_ERROPRO VARCHAR(MAX)
	)	
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TS_CONFI')
BEGIN
	CREATE TABLE TS_CONFI(
		CD_CONFIGU INT PRIMARY KEY IDENTITY NOT NULL,
		DS_CONFIGU VARCHAR(250) NOT NULL,
		TP_CONFIGU VARCHAR(5) NOT NULL,
		LG_CONFIGU VARCHAR(1) NOT NULL
	)	
END